name: PR Deployment

on:
  pull_request:
    paths:
      - "src/web-admin/**"
      - "src/web-site/**"
      - "src/web-supervisor/**"

env:
  ALLOWED_PATHS: "src/web-admin src/web-site src/web-supervisor"
  STAGING_HOST_PREFIX: "staging-pr"
  STAGING_HOST_DOMAIN: "sample.com"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: azure cli login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Get Changed Folders
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git fetch origin

          IFS=' ' read -ra ALLOWED_PATHS_ARR <<< "$ALLOWED_PATHS"

          PR_NUMBER=${{ github.event.pull_request.number }}
          BASE_REF=${{ github.event.pull_request.base.ref }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}

          CHANGED_DIRS=$(git diff --name-only origin/${BASE_REF}..${HEAD_SHA} | \
            xargs -n1 dirname | \
            while read -r dir; do
              for allowed in "${ALLOWED_PATHS_ARR[@]}"; do
                if [[ "$dir" == "$allowed" || "$dir" == "$allowed"/* ]]; then
                  echo "$dir"
                  break
                fi
              done
            done | tr '\n' ' ' || true)

          echo "Modifying ingress.yml..."
          for folder in ${CHANGED_DIRS// /$'\n'}; do
            STAGING_HOST="staging-${PR_NUMBER}-${folder#src/web-}-$(openssl rand -hex 3).sample.com"
            url=$(cat README.md | grep "${folder}" | grep -o "https://[^)]*" | cut -d" " -f1 | sed -e 's|https://||' -e 's|/.*$||')

            if [ -n "$url" ]; then
              yq ".spec.rules[] | select(.host == \"${url}\") | .host = \"${STAGING_HOST}\"" .iac/ingress.yml | sed '1s/^/- /;2s/^/  /' | sed 's/^/    /' >> .iac/ingress.yml
              yq ".spec.tls[].hosts += [\"${STAGING_HOST}\"]" .iac/ingress.yml > /tmp/ingress.yml && mv /tmp/ingress.yml .iac/ingress.yml
              sleep 1

            COMMENT="🚀 **PR Preview Environment Deployed!**%0A- **New Host:** [${STAGING_HOST}](https://${STAGING_HOST})"

            curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/json" \
              -d "{\"body\": \"$COMMENT\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

            # curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/dns_records" \
            #   -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            #   -H "Content-Type: application/json" \
            #   --data '{
            #     "type": "CNAME",
            #     "name": "'$staging_host'",
            #     "content": "gap.ulak.com",
            #     "ttl": 3600,
            #     "proxied": true
            #   }'
            else
              echo "${folder} url not found in README.md"
              exit 1
            fi
          done

      - name: Announce New Hosts to Cloudflare
        run: |
          exit 0;
